version: '3'

services:
  db:
    container_name: mysql-8
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: symfony_docker
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - '3307:3306'
    volumes:
      - 'db_app:/var/lib/mysql'

  php:
    container_name: php-8
    build:
      context: ./php
    ports:
      - '9000:9000'
    volumes:
      - ../:/var/www/symfony
    networks:
      - symfony

  nginx:
    container_name: nginx-latest
    build:
      context: ./nginx
    ports:
      - '8080:80'
    volumes:
      - ../:/var/www/symfony
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - db

volumes:
  db_app:


networks:
  symfony:
